/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ImageToImageImport } from './routes/image-to-image'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ImageToImageRoute = ImageToImageImport.update({
  id: '/image-to-image',
  path: '/image-to-image',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/image-to-image': {
      id: '/image-to-image'
      path: '/image-to-image'
      fullPath: '/image-to-image'
      preLoaderRoute: typeof ImageToImageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-to-image': typeof ImageToImageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-to-image': typeof ImageToImageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/image-to-image': typeof ImageToImageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/image-to-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/image-to-image'
  id: '__root__' | '/' | '/image-to-image'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageToImageRoute: typeof ImageToImageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageToImageRoute: ImageToImageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/image-to-image"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/image-to-image": {
      "filePath": "image-to-image.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
